/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package leeyaprende;

/**
 *
 * @author Carlos
 */
public class Menu extends javax.swing.JFrame {
    

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu8 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu10 = new javax.swing.JMenu();
        jMenu11 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Usuario = new javax.swing.JMenu();
        agregarUsuario = new javax.swing.JMenuItem();
        consultarUsuarios = new javax.swing.JMenuItem();
        Libro = new javax.swing.JMenu();
        agregarLibro = new javax.swing.JMenuItem();
        consultarLibro = new javax.swing.JMenuItem();
        editoriales = new javax.swing.JMenu();
        agregarEditorial = new javax.swing.JMenuItem();
        consultarEditorial = new javax.swing.JMenuItem();
        autor = new javax.swing.JMenu();
        agregarAutor = new javax.swing.JMenuItem();
        cosnultarAutores = new javax.swing.JMenuItem();
        area = new javax.swing.JMenu();
        agregarArea = new javax.swing.JMenuItem();
        consultarArea = new javax.swing.JMenuItem();
        prestamo = new javax.swing.JMenu();
        agragarPrestamo = new javax.swing.JMenuItem();
        consultarPrestamo = new javax.swing.JMenuItem();
        jMenu13 = new javax.swing.JMenu();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenu3.setText("jMenu3");

        jMenuItem8.setText("jMenuItem8");

        jMenuItem14.setText("jMenuItem14");

        jMenu8.setText("File");
        jMenuBar2.add(jMenu8);

        jMenu9.setText("Edit");
        jMenuBar2.add(jMenu9);

        jMenu10.setText("File");
        jMenuBar3.add(jMenu10);

        jMenu11.setText("Edit");
        jMenuBar3.add(jMenu11);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lee & Aprende");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icono.png")).getImage());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo.png"))); // NOI18N

        Usuario.setText("Usuarios");
        Usuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        agregarUsuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        agregarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/2_1.png"))); // NOI18N
        agregarUsuario.setText("Agregar nuevo usuario");
        agregarUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        agregarUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                agregarUsuarioMouseClicked(evt);
            }
        });
        agregarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarUsuarioActionPerformed(evt);
            }
        });
        Usuario.add(agregarUsuario);

        consultarUsuarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.CTRL_MASK));
        consultarUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/8.png"))); // NOI18N
        consultarUsuarios.setText("Consultar usuarios");
        consultarUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        consultarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarUsuariosActionPerformed(evt);
            }
        });
        Usuario.add(consultarUsuarios);

        jMenuBar1.add(Usuario);

        Libro.setText("Libros");
        Libro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        agregarLibro.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        agregarLibro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/5_2.png"))); // NOI18N
        agregarLibro.setText("Agregar nuevo libro");
        agregarLibro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        agregarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarLibroActionPerformed(evt);
            }
        });
        Libro.add(agregarLibro);

        consultarLibro.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        consultarLibro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/8.png"))); // NOI18N
        consultarLibro.setText("Consultar libros");
        consultarLibro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        consultarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarLibroActionPerformed(evt);
            }
        });
        Libro.add(consultarLibro);

        jMenuBar1.add(Libro);

        editoriales.setText("Editoriales");
        editoriales.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        agregarEditorial.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        agregarEditorial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/5_2.png"))); // NOI18N
        agregarEditorial.setText("Agregar nueva editorial");
        agregarEditorial.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        agregarEditorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarEditorialActionPerformed(evt);
            }
        });
        editoriales.add(agregarEditorial);

        consultarEditorial.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        consultarEditorial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/8.png"))); // NOI18N
        consultarEditorial.setText("Consultar editoriales");
        consultarEditorial.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        consultarEditorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarEditorialActionPerformed(evt);
            }
        });
        editoriales.add(consultarEditorial);

        jMenuBar1.add(editoriales);

        autor.setText("Autores");
        autor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        agregarAutor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        agregarAutor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/5_2.png"))); // NOI18N
        agregarAutor.setText("Agregar nuevo autor");
        agregarAutor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        agregarAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarAutorActionPerformed(evt);
            }
        });
        autor.add(agregarAutor);

        cosnultarAutores.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        cosnultarAutores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/8.png"))); // NOI18N
        cosnultarAutores.setText("Consultar autores");
        cosnultarAutores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cosnultarAutores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cosnultarAutoresActionPerformed(evt);
            }
        });
        autor.add(cosnultarAutores);

        jMenuBar1.add(autor);

        area.setText("Áreas");
        area.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        agregarArea.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        agregarArea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/5_2.png"))); // NOI18N
        agregarArea.setText("Agregar nueva área");
        agregarArea.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        agregarArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarAreaActionPerformed(evt);
            }
        });
        area.add(agregarArea);

        consultarArea.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        consultarArea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/8.png"))); // NOI18N
        consultarArea.setText("Consultar áreas");
        consultarArea.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        consultarArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarAreaActionPerformed(evt);
            }
        });
        area.add(consultarArea);

        jMenuBar1.add(area);

        prestamo.setText("Prestamos");
        prestamo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        agragarPrestamo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        agragarPrestamo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/6_1.png"))); // NOI18N
        agragarPrestamo.setText("Agregar nuevo prestamo");
        agragarPrestamo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        agragarPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agragarPrestamoActionPerformed(evt);
            }
        });
        prestamo.add(agragarPrestamo);

        consultarPrestamo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        consultarPrestamo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/8.png"))); // NOI18N
        consultarPrestamo.setText("Consultar prestamos");
        consultarPrestamo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        consultarPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarPrestamoActionPerformed(evt);
            }
        });
        prestamo.add(consultarPrestamo);

        jMenuBar1.add(prestamo);

        jMenu13.setText("Multas");
        jMenu13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jMenuItem17.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/13.png"))); // NOI18N
        jMenuItem17.setText("Consultar multas");
        jMenuItem17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17ActionPerformed(evt);
            }
        });
        jMenu13.add(jMenuItem17);

        jMenuBar1.add(jMenu13);

        jMenu7.setText("Cerrar sesión");
        jMenu7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu7MouseClicked(evt);
            }
        });
        jMenu7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu7ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu7);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(104, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(104, 104, 104))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarUsuarioActionPerformed
        Usuario usuario = new Usuario();
        usuario.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_agregarUsuarioActionPerformed

    private void jMenu7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu7ActionPerformed
        
    }//GEN-LAST:event_jMenu7ActionPerformed

    private void jMenu7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu7MouseClicked
        new Inicio().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenu7MouseClicked

    private void agregarUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarUsuarioMouseClicked
       
    }//GEN-LAST:event_agregarUsuarioMouseClicked

    private void agregarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarLibroActionPerformed
        // TODO add your handling code here:
        Libro libro = new Libro();
        libro.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_agregarLibroActionPerformed

    private void agregarEditorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarEditorialActionPerformed
        // TODO add your handling code here:
        Editorial editorial = new Editorial();
        editorial.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_agregarEditorialActionPerformed

    private void agregarAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarAutorActionPerformed
        // TODO add your handling code here:
        Autor autor = new Autor();
        autor.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_agregarAutorActionPerformed

    private void agregarAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarAreaActionPerformed
        // TODO add your handling code here:
        Area area = new Area();
        area.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_agregarAreaActionPerformed

    private void consultarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarLibroActionPerformed
        new ConsultarLibros().setVisible(true);
       
    }//GEN-LAST:event_consultarLibroActionPerformed

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed
        new Multa().setVisible(true);
        
    }//GEN-LAST:event_jMenuItem17ActionPerformed

    private void consultarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarUsuariosActionPerformed
        // TODO add your handling code here:
        new ConsultarUsuarios().setVisible(true);
        
    }//GEN-LAST:event_consultarUsuariosActionPerformed

    private void consultarEditorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarEditorialActionPerformed
        new ConsultarEditoriales().setVisible(true);
        
    }//GEN-LAST:event_consultarEditorialActionPerformed

    private void cosnultarAutoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cosnultarAutoresActionPerformed
        new ConsultarAutores().setVisible(true);
        
    }//GEN-LAST:event_cosnultarAutoresActionPerformed

    private void consultarAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarAreaActionPerformed
        new ConsultarAreas().setVisible(true);
        
    }//GEN-LAST:event_consultarAreaActionPerformed

    private void consultarPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarPrestamoActionPerformed
        new ConsultarPrestamos().setVisible(true);
        
    }//GEN-LAST:event_consultarPrestamoActionPerformed

    private void agragarPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agragarPrestamoActionPerformed
        new Prestamo().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_agragarPrestamoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Libro;
    private javax.swing.JMenu Usuario;
    private javax.swing.JMenuItem agragarPrestamo;
    private javax.swing.JMenuItem agregarArea;
    private javax.swing.JMenuItem agregarAutor;
    private javax.swing.JMenuItem agregarEditorial;
    private javax.swing.JMenuItem agregarLibro;
    private javax.swing.JMenuItem agregarUsuario;
    private javax.swing.JMenu area;
    private javax.swing.JMenu autor;
    private javax.swing.JMenuItem consultarArea;
    private javax.swing.JMenuItem consultarEditorial;
    private javax.swing.JMenuItem consultarLibro;
    private javax.swing.JMenuItem consultarPrestamo;
    private javax.swing.JMenuItem consultarUsuarios;
    private javax.swing.JMenuItem cosnultarAutores;
    private javax.swing.JMenu editoriales;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JMenu prestamo;
    // End of variables declaration//GEN-END:variables
}
